config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  devise_for :users
  root to: "welcome#index"
  get 'my_portfolio', to: "users#my_portfolio"
  get 'my_friends', to: "users#my_friends"
  get 'search_friends', to: "users#search_friends"
  get 'search_stock', to: "stocks#search"
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
require 'net/http'
require 'json'

class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true

  BASE_URI = 'https://www.alphavantage.co'

  def self.company_lookup(ticker_symbol)
    response = get("/query?function=OVERVIEW&symbol=#{ticker_symbol}&apikey=#{ENV['API_KEY']}")
    handle_response(response)['Name']
  end

  def self.new_lookup(ticker_symbol)
    response = get("/query?function=GLOBAL_QUOTE&symbol=#{ticker_symbol}&apikey=#{ENV['API_KEY']}")

        if response.is_a?(Net::HTTPSuccess)
      quote = JSON.parse(response.body)['Global Quote']
      if quote && quote['05. price']
        last_price = quote['05. price']
        name = company_lookup(ticker_symbol)
        if name
          new(ticker: ticker_symbol, name: name, last_price: last_price)
        else
          Rails.logger.error "Failed to fetch company name for ticker: #{ticker_symbol}"
          nil
        end
      else
        Rails.logger.error "Quote data not found for ticker: #{ticker_symbol}"
        nil
      end
    else
      Rails.logger.error "Stock lookup failed for ticker: #{ticker_symbol}"
      nil
    end
  end

  def self.check_db(ticker_symbol)
    Stock.where(ticker: ticker_symbol).first
  end

  private

  def self.api_key
    ENV['API_KEY']
  end

  def self.get(path)
    uri = URI("#{BASE_URI}#{path}")
    Net::HTTP.get_response(uri)
  end

  def self.handle_response(response)
    if response.is_a?(Net::HTTPSuccess)
      JSON.parse(response.body)
    else
      Rails.logger.error "API request failed: #{response.code} - #{response.message}"
      nil
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def stock_already_tracked?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end

  def under_stock_limit?
    stocks.count < 10
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

  include PgSearch::Model

  pg_search_scope :search_by_first_and_last_name,
    against: [ :first_name, :last_name ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  def self.search_by_first_and_last_name_excluding_current_user(query, current_user_id)
    search_by_first_and_last_name(query).where.not(id: current_user_id)
  end

  def not_friends_with?(id_friends)
    !friends.where(id: id_friends).exists?
  end

end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def create
    friend = User.find(params[:friend_id])
    current_user.friends << friend

    if current_user.save
      flash[:notice] = "follow"
    else
      flash[:notice] = "something wrong"
    end
    redirect_to my_friends_path
  end

  def destroy
    friendship = current_user.friendships.where(friend_id: params[:id]).first
    friendship.destroy
    flash[:notice] = "unfollow"
    redirect_to my_friends_path
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  # @stock = Stock.new_lookup(params[:stock])
  def search
    @user = current_user
    @tracked_stocks = current_user.stocks
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])

      if @stock
        render 'users/my_portfolio'
      else
        flash[:alert] = "Please enter a valid symbol to search"
        redirect_to my_portfolio_path
      end
    else
      flash[:alert] = "Please enter a symbol to search"
      redirect_to my_portfolio_path
    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

  def create
    stock = Stock.check_db(params[:ticker])
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])
      if stock.save
        flash[:notice] = "Stock #{stock.name} added"
      else
        flash[:alert] = "There was an error saving the stock"
        redirect_to my_portfolio_path and return
      end
    end
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice] = "Stock #{stock.name} ajouté"
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
    user_stock.destroy
    flash[:notice] = "#{stock.ticker} remove"
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user = current_user
    @tracked_stocks = current_user.stocks
  end

  def my_friends
    @friends = current_user.friends
    if params[:query].present?
      @users = User.all.search_by_first_and_last_name_excluding_current_user(params[:query], current_user.id)
    end
  end

  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index ]

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/friends/_list.html.erb
  <div class="row mt-5">
    <div class="col-9">
        <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th scope="col">Email</th>
            <th scope="col">Prenom</th>
            <th scope="col">Nom</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @friends.each do |friend|  %>
            <tr>
              <th scope="row"><%= friend.email %></th>
              <td><%= friend.first_name %></td>
              <td><%= friend.last_name %></td>
              <td>
                <%= link_to "Profil", user_path(friend),
                    class: "btn btn-success btn-sm"
                %>
                <%= link_to "Unfollow", friendship_path(friend),
                    data: { turbo_method: :delete},
                    class: "btn btn-warning btn-sm"
                %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockTracker</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container" style="margin-top: 30px">
      <%= render "shared/flashes" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">

   <%= link_to root_path, class: "navbar-brand" do %>
      <div class="image-wrapper">
        <%= image_tag "euro.jpeg", alt: "Euro Logo", class: "transparent-image" %>
      </div>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Mes amis", my_friends_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to current_user.first_name, "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://avatars.githubusercontent.com/u/126069860?v=4", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Edit", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/stocks/_list.html.erb
  <div class="row mt-5">
    <div class="col-9">
        <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th scope="col">Ticker</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @tracked_stocks.each do |stock|  %>
            <tr>
              <th scope="row"><%= stock.ticker %></th>
              <td><%= stock.name %></td>
              <td><%= stock.last_price %></td>
              <td>
                  <%= form_with url: user_stocks_path, method: :post, local: true do |form| %>
                    <%= form.hidden_field :user, value: current_user.id %>
                    <%= form.hidden_field :ticker, value: stock.ticker %>
                    <% if current_user.can_track_stock?(stock.ticker) %>
                      <%= form.submit 'Add to portfolio', class: "btn btn-xs btn-success" %>
                    <% elsif current_user.id != @user.id %>
                      <span class="badge badge-primary">
                        Already tracking
                        <% if !current_user.under_stock_limit? %>
                          10 stocks
                        <% end %>
                        <% if current_user.stock_already_tracked?(stock.ticker) %>
                          this stock
                        <% end %>
                      </span>
                    <% end %>
                  <% end %>
                  <% if current_user.id == @user.id %>
                    <%= link_to "Remove", user_stock_path(stock),
                        data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                        class: "btn btn-success btn-sm"
                    %>
                  <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

app/views/users/_form.html.erb
  <%= form_tag search_stock_path, method: :get do%>
    <div class="form_group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :stock, params[:stock], placeholder: "Symbole d'action", autofocus: true, class:"form-control form-control-lg"%>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class:"btn btn-success btn-lg" do  %>
          <i class="fa-solid fa-magnifying-glass" style="color: #fcfcfc;"></i>
        <% end %>
      </div>
    </div>
  <% end %>

app/views/users/_friends.html.erb
    <div class="card card-header results-block">
      <table class="col-md-12">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><strong>Email: </strong> <%= user.email %></td>
              <td><strong>Prenom: </strong> <%= user.first_name %></td>
              <td><strong>Nom: </strong> <%= user.last_name %></td>
              <td>
                <strong>Actions: </strong>
                <%= link_to "Profil", user_path(user),
                  class: "btn btn-sm btn-success"
                %>
                <% if current_user.not_friends_with?(user.id) %>
                  <%= button_to "follow", friendships_path(friend_id: user.id),
                    class: "btn btn-sm btn-success", method: :post
                  %>
                <% else %>
                  <span class="badge badge-secondary">Already friend</span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

app/views/users/_result.html.erb
<% if @stock %>
  <div class="card card-header results-block">
    <strong>Symbol: </strong> <%= @stock.ticker %>
    <strong>Name: </strong> <%= @stock.name %>
    <strong>Price: </strong> <%= @stock.last_price %>
    <%= form_with url: user_stocks_path, method: :post, local: true do |form| %>
      <%= form.hidden_field :user, value: current_user.id %>
      <%= form.hidden_field :ticker, value: @stock.ticker %>
      <% if current_user.can_track_stock?(@stock.ticker) %>
        <%= form.submit 'Add to portfolio', class: "btn btn-xs btn-success" %>
      <% else %>
        <span class="badge badge-primary">
          Already tracking
          <% if !current_user.under_stock_limit? %>
            10 stocks
          <% end %>
          <% if current_user.stock_already_tracked?(@stock.ticker) %>
            this stock
          <% end %>
        </span>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/users/my_friends.html.erb
  <h1>Mes Amis</h1>

  <%= form_tag my_friends_path, method: :get do%>
    <div class="form_group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :query, params[:query], placeholder: "Rechercher un amis", autofocus: true, class:"form-control form-control-lg"%>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class:"btn btn-success btn-lg" do  %>
          <i class="fa-solid fa-magnifying-glass" style="color: #fcfcfc;"></i>
        <% end %>
      </div>
    </div>
  <% end %>

  <% if @users%>
    <%= render 'users/friends'  %>
  <% end %>
  <% if !@friends.empty? %>
    <%= render 'friends/list'  %>
  <% end %>

app/views/users/my_portfolio.html.erb
<h1>Mon Portefeuille</h1>

<div class="search-area container"  data-controller="return-search">
  <h3>Recherche</h3>
  <%= form_tag search_stock_path, data: {return_search_target: "form", action: "submit->return-search#send"}, method: :get do%>
    <div class="form_group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :stock, params[:stock], placeholder: "Symbole d'action", autofocus: true, class:"form-control form-control-lg"%>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class:"btn btn-success btn-lg" do  %>
          <i class="fa-solid fa-magnifying-glass" style="color: #fcfcfc;"></i>
        <% end %>
      </div>
    </div>
  <% end %>
  <% if @stock %>
    <%= render 'users/result'  %>
  <% end %>

  <% if !@tracked_stocks.empty? %>
    <%= render 'stocks/list'  %>
  <% end %>
</div>

app/views/users/show.html.erb
<h2>Profil</h2>
<div class="card card-header results-block">
  <table class="col-md-12">
    <tbody>
      <tr>
        <td><strong>Email: </strong> <%= @user.email %></td>
        <td><strong>Prenom: </strong> <%= @user.first_name %></td>
        <td><strong>Nom: </strong> <%= @user.last_name %></td>
        <td>
          <% if current_user.not_friends_with?(@user.id) %>
            <%= button_to "follow", friendships_path(friend_id: @user.id),
              class: "btn btn-sm btn-success", method: :post
            %>
          <% else %>
            <span class="badge badge-secondary">Already friend</span>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

  <% if !@tracked_stocks.empty? %>
    <%= render 'stocks/list'  %>
  <% else %>
    <p class="lead">n'a pas d'actions</p>
  <% end %>

app/views/welcome/index.html.erb
  <div class="container mt-5">
    <div class="jumbotron text-center">
      <h1 class="display-4">Bienvenue sur Stock Tracker</h1>
      <p class="lead">Gérez votre portefeuille d'actions facilement.</p>
      <hr class="my-4">
      <%= link_to 'Mon Portefeuille', my_portfolio_path, class: 'btn btn-success btn-lg' %>
    </div>
  </div>